<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5e850f5e-3d28-4f57-bc41-700707056a6b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Assessment.Application\Assessment.Application.csproj" />
    <ProjectReference Include="..\Assessment.Infrastructure\Assessment.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BuildingBlocks.Application">
      <HintPath>..\..\..\shared\BuildingBlocks\BuildingBlocks.Application\bin\Debug\net8.0\BuildingBlocks.Application.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
