<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BuildingBlocks.Application">
      <HintPath>..\..\..\..\shared\BuildingBlocks\BuildingBlocks.Application\bin\Debug\net8.0\BuildingBlocks.Application.dll</HintPath>
    </Reference>
    <Reference Include="BuildingBlocks.Domain">
      <HintPath>..\..\..\..\shared\BuildingBlocks\BuildingBlocks.Domain\bin\Debug\net8.0\BuildingBlocks.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
