<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Assessment.Application\Assessment.Application.csproj" />
    <ProjectReference Include="..\Assessment.Domain\Assessment.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BuildingBlocks.Application">
      <HintPath>..\..\..\shared\BuildingBlocks\BuildingBlocks.Application\bin\Debug\net8.0\BuildingBlocks.Application.dll</HintPath>
    </Reference>
    <Reference Include="BuildingBlocks.Domain">
      <HintPath>..\..\..\shared\BuildingBlocks\BuildingBlocks.Domain\bin\Debug\net8.0\BuildingBlocks.Domain.dll</HintPath>
    </Reference>
    <Reference Include="BuildingBlocks.Messaging">
      <HintPath>..\..\..\shared\BuildingBlocks\BuildingBlocks.Messaging\bin\Debug\net8.0\BuildingBlocks.Messaging.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
